

//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using OA.EFDAL;
using OA.IDAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Reflection;
using System.Configuration;
using System.Web;

namespace OA.DALFactory
{
    public partial class StaticDalFactory
    {

		public static IOrderInfoDal GetOrderInfoDal()
        {
            IOrderInfoDal OrderInfoDal = HttpRuntime.Cache["OrderInfoDal"] as IOrderInfoDal;
            if (OrderInfoDal == null)
            {
                OrderInfoDal = Assembly.Load(assembly).CreateInstance(assembly + ".OrderInfoDal") as IOrderInfoDal;
                HttpRuntime.Cache["OrderInfoDal"] = OrderInfoDal;
            }
            return OrderInfoDal;
        }

		public static IUserInfoDal GetUserInfoDal()
        {
            IUserInfoDal UserInfoDal = HttpRuntime.Cache["UserInfoDal"] as IUserInfoDal;
            if (UserInfoDal == null)
            {
                UserInfoDal = Assembly.Load(assembly).CreateInstance(assembly + ".UserInfoDal") as IUserInfoDal;
                HttpRuntime.Cache["UserInfoDal"] = UserInfoDal;
            }
            return UserInfoDal;
        }

}
}
